# Generated by Django 6.1 on 2026-10-07 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_usuarios', '0001_initial'),
        ('centros', '0001_initial'),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilextendido',
            name='centro',
            field=models.ForeignKey(blank=True, help_text='Centro de emergencia al que está asignado el operador o médico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='centros.centroemergencia', verbose_name='Centro asignado'),
        ),
        migrations.AddField(
            model_name='perfilextendido',
            name='medico',
            field=models.ForeignKey(blank=True, help_text='Ficha del médico si el rol es MEDICO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='clinica.medico', verbose_name='Médico asignado'),
        ),
        migrations.AddField(
            model_name='perfilextendido',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR_CENTRO', 'Operador de Centro'), ('MEDICO', 'Médico Especialista'), ('PACIENTE', 'Paciente')], default='PACIENTE', help_text='Rol de acceso para control de permisos (RBAC).', max_length=20, verbose_name='Rol en la plataforma'),
        ),
    ]
