# Generated by Django 6.1 on 2026-10-02 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(blank=True, null=True, verbose_name='ID de usuario registrado')),
                ('nombre_invitado', models.CharField(blank=True, default='', max_length=120, verbose_name='Nombre del invitado')),
                ('telefono_invitado', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono del invitado')),
                ('modo', models.CharField(choices=[('aviso', 'Voy en camino'), ('solicitud', 'Solicitar turno urgente')], default='solicitud', max_length=10, verbose_name='Modo de solicitud')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo breve')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado por el centro'), ('en_camino', 'Paciente en camino'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('lat_usuario', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud del usuario')),
                ('lon_usuario', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud del usuario')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='centros.centroemergencia', verbose_name='Centro de emergencia')),
            ],
            options={
                'verbose_name': 'Solicitud de atención',
                'verbose_name_plural': 'Solicitudes de atención',
                'db_table': 'solicitudes_atencion',
                'ordering': ['-creado_en'],
            },
        ),
    ]
