# Generated by Django 6.1 on 2026-10-07 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
        ('centros', '0002_especialidad_centroespecialidad_and_more'),
        ('clinica', '0003_disponibilidadmedico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudatencion',
            name='atendido_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de atención'),
        ),
        migrations.AddField(
            model_name='solicitudatencion',
            name='derivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_derivadas_operador', to=settings.AUTH_USER_MODEL, verbose_name='Operador que derivó'),
        ),
        migrations.AddField(
            model_name='solicitudatencion',
            name='diagnostico',
            field=models.TextField(blank=True, default='', verbose_name='Diagnóstico médico'),
        ),
        migrations.AddField(
            model_name='solicitudatencion',
            name='especialidad_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_derivadas', to='centros.especialidad', verbose_name='Especialidad asignada'),
        ),
        migrations.AddField(
            model_name='solicitudatencion',
            name='fecha_derivacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de derivación'),
        ),
        migrations.AddField(
            model_name='solicitudatencion',
            name='indicaciones',
            field=models.TextField(blank=True, default='', verbose_name='Indicaciones médicas'),
        ),
        migrations.AddField(
            model_name='solicitudatencion',
            name='medico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_derivadas', to='clinica.medico', verbose_name='Médico asignado'),
        ),
        migrations.AddField(
            model_name='solicitudatencion',
            name='observaciones_triage',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones de triage'),
        ),
        migrations.AddField(
            model_name='solicitudatencion',
            name='prioridad',
            field=models.CharField(default='media', max_length=20, verbose_name='Prioridad de triage'),
        ),
        migrations.AlterField(
            model_name='solicitudatencion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado por el centro'), ('en_camino', 'Paciente en camino'), ('derivado', 'Derivado a especialista'), ('en_atencion', 'En atención médica'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
    ]
