# Generated by Django 6.1 on 2026-09-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre y apellido del medico')),
                ('especialidad', models.CharField(choices=[('clinica_medica', 'Clinica medica'), ('pediatria', 'Pediatria'), ('cardiologia', 'Cardiologia'), ('traumatologia', 'Traumatologia'), ('ginecologia', 'Ginecologia'), ('otra', 'Otra')], default='clinica_medica', max_length=20)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'db_table': 'medicos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre y apellido del paciente')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI del paciente')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono de contacto')),
                ('obra_social', models.CharField(blank=True, default='', max_length=80, verbose_name='Obra social o prepaga')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
    ]
