# Generated by Django 6.1 on 2026-10-07 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0002_especialidad_centroespecialidad_and_more'),
        ('clinica', '0002_medico_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.SmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='0=Lunes, 1=Martes, ..., 6=Domingo', verbose_name='Día de la semana (0=Lunes, 6=Domingo)')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio de guardia')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin de guardia')),
                ('en_guardia_activa', models.BooleanField(default=True, verbose_name='En guardia activa programada')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias_programadas', to='centros.centroemergencia', verbose_name='Centro de emergencia')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardias', to='clinica.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Disponibilidad / Guardia de médico',
                'verbose_name_plural': 'Disponibilidades / Guardias de médicos',
                'db_table': 'disponibilidad_medicos',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
