# Generated by Django 6.1 on 2026-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del centro')),
                ('tipo', models.CharField(choices=[('hospital', 'Hospital público'), ('upa', 'UPA / Sala de primeros auxilios'), ('same', 'SAME / Ambulancia'), ('bomberos', 'Bomberos'), ('policia', 'Policía'), ('otro', 'Otro')], default='hospital', max_length=20, verbose_name='Tipo de servicio')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('ciudad', models.CharField(default='Posadas', max_length=100, verbose_name='Ciudad')),
                ('provincia', models.CharField(default='Misiones', max_length=100, verbose_name='Provincia')),
                ('pais', models.CharField(default='Argentina', max_length=60, verbose_name='País')),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitud')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('atiende_24h', models.BooleanField(default=True, verbose_name='Atiende 24 horas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
            ],
            options={
                'verbose_name': 'Centro de emergencia',
                'verbose_name_plural': 'Centros de emergencia',
                'db_table': 'centros_emergencia',
                'ordering': ['nombre'],
            },
        ),
    ]
