# Generated by Django 6.1 on 2026-10-07 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0001_initial'),
        ('clinica', '0002_medico_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.SlugField(unique=True, verbose_name='Código slug')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, default='', max_length=50, verbose_name='Ícono')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CentroEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo en este centro')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centro_especialidades', to='centros.centroemergencia', verbose_name='Centro')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_adheridos', to='centros.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Especialidad de centro',
                'verbose_name_plural': 'Especialidades de centros',
                'db_table': 'centro_especialidades',
                'unique_together': {('centro', 'especialidad')},
            },
        ),
        migrations.AddField(
            model_name='centroemergencia',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='centros', through='centros.CentroEspecialidad', to='centros.especialidad'),
        ),
        migrations.CreateModel(
            name='AsignacionMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos_asignados', to='centros.centroemergencia', verbose_name='Centro')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_centro', to='clinica.medico', verbose_name='Médico')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos_asignados', to='centros.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Asignación de médico a centro',
                'verbose_name_plural': 'Asignaciones de médicos a centros',
                'db_table': 'asignaciones_medicos',
                'unique_together': {('medico', 'centro', 'especialidad')},
            },
        ),
    ]
