# Generated by Django 6.1 on 2026-08-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=120, verbose_name='Nombre y apellido del paciente')),
                ('paciente_dni', models.CharField(max_length=10, verbose_name='DNI del paciente')),
                ('paciente_telefono', models.CharField(max_length=30, verbose_name='Telefono de contacto')),
                ('obra_social', models.CharField(blank=True, default='', max_length=80, verbose_name='Obra social o prepaga')),
                ('profesional', models.CharField(max_length=120, verbose_name='Profesional que atiende')),
                ('especialidad', models.CharField(choices=[('clinica_medica', 'Clinica medica'), ('pediatria', 'Pediatria'), ('cardiologia', 'Cardiologia'), ('traumatologia', 'Traumatologia'), ('ginecologia', 'Ginecologia'), ('otra', 'Otra')], default='clinica_medica', max_length=20)),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora del turno')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_atencion', 'En atencion'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado'), ('ausente', 'Paciente ausente')], default='pendiente', max_length=20)),
                ('motivo_consulta', models.TextField(blank=True, default='', verbose_name='Motivo de la consulta')),
                ('diagnostico', models.TextField(blank=True, default='', verbose_name='Diagnostico registrado')),
                ('indicaciones', models.TextField(blank=True, default='', verbose_name='Indicaciones y tratamiento')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='turnos_fecha_h_f4f609_idx'), models.Index(fields=['estado'], name='turnos_estado_e53de7_idx'), models.Index(fields=['paciente_dni'], name='turnos_pacient_f24d98_idx')],
            },
        ),
    ]
