# Generated by Django 6.1 on 2026-09-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField(help_text='Referencia desacoplada al módulo Clínica', verbose_name='ID del Paciente')),
                ('medico_id', models.IntegerField(help_text='Referencia desacoplada al módulo Clínica', verbose_name='ID del Médico')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora del turno')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_atencion', 'En atencion'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado'), ('ausente', 'Paciente ausente')], default='pendiente', max_length=20)),
                ('motivo_consulta', models.TextField(blank=True, default='', verbose_name='Motivo de la consulta')),
                ('diagnostico', models.TextField(blank=True, default='', verbose_name='Diagnostico registrado')),
                ('indicaciones', models.TextField(blank=True, default='', verbose_name='Indicaciones y tratamiento')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='turnos_fecha_h_f4f609_idx'), models.Index(fields=['estado'], name='turnos_estado_e53de7_idx'), models.Index(fields=['paciente_id'], name='turnos_pacient_94168c_idx')],
            },
        ),
    ]
