# Generated by Django 6.1 on 2026-09-29 23:03

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="turno",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("profesional"),
                models.F("fecha_hora"),
                condition=models.Q(("estado", "cancelado"), _negated=True),
                name="turno_unico_por_profesional_y_horario",
            ),
        ),
    ]
