# Generated by Django 6.1 on 2026-10-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0002_desacoplar_clinica"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="turno",
            constraint=models.UniqueConstraint(
                models.F("medico_id"),
                models.F("fecha_hora"),
                condition=models.Q(("estado", "cancelado"), _negated=True),
                name="turno_unico_por_medico_y_horario",
            ),
        ),
    ]
